# Site settings
title: Warehouse Now > Stock Management Software &amp; WMS
email: joncarlmatthews@gmail.com
description: "Warehouse Now | Stock Management Software | WMS"
baseurl: ""
url: "http://warehouse-now.com"

# Build settings
markdown: kramdown
permalink: pretty
